version: "2.1"
services:
  db:
    image: edxops/mysql:5.7
    container_name: enterprise-subsidy.db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - devstack_default
    volumes:
      - enterprise_subsidy_mysql57:/var/lib/mysql

  mysql80:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: enterprise-subsidy.mysql80
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    # Oracle-packaged version includes a `linux/arm64/v8` version, needed for
    # machines with Apple Silicon CPUs (Mac M1, M2)
    image: mysql:8.0.33-oracle
    networks:
      - devstack_default
    ports:
      - "3406:3306"
    volumes:
      - enterprise_subsidy_mysql80:/var/lib/mysql

  memcache:
    image: memcached:1.4.24
    container_name: enterprise-subsidy.memcache
    networks:
      - devstack_default
    command: memcached -vv

  app:
    # Uncomment this line to use the official enterprise-subsidy base image
    # image: openedx/enterprise-subsidy
    image: openedx/enterprise-subsidy:latest-devstack
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enterprise-subsidy.app
    volumes:
      - .:/edx/app/enterprise-subsidy
      - ../src:/edx/src

    command: bash -c 'while true; do python /edx/app/enterprise-subsidy/manage.py runserver 0.0.0.0:18280; sleep 2; done'
    environment:
      DJANGO_SETTINGS_MODULE: enterprise_subsidy.settings.devstack
      ENABLE_DJANGO_TOOLBAR: 1
    ports:
      - "18280:18280" # TODO: change this to your port
    networks:
      - devstack_default
    stdin_open: true
    tty: true

networks:
  devstack_default:
    external: true

volumes:
  enterprise_subsidy_mysql57:
  enterprise_subsidy_mysql80:
