version: "2.1"
services:
  db:
    image: edxops/mysql:5.7
    container_name: enterprise-subsidy.db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - devstack_default
    volumes:
      - enterprise_subsidy_mysql57:/var/lib/mysql

  memcache:
    image: memcached:1.4.24
    container_name: enterprise-subsidy.memcache
    networks:
      - devstack_default
    command: memcached -vv

  app:
    image: openedx/enterprise-subsidy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enterprise-subsidy.app
    volumes:
      - .:/edx/app/enterprise-subsidy
      - ../src:/edx/src

    command: bash -c 'while true; do python /edx/app/enterprise-subsidy/manage.py runserver 0.0.0.0:18280; sleep 2; done'
    environment:
      DJANGO_SETTINGS_MODULE: enterprise_subsidy.settings.devstack
      ENABLE_DJANGO_TOOLBAR: 1
    ports:
      - "18280:18280" # TODO: change this to your port
    networks:
      - devstack_default
    stdin_open: true
    tty: true

networks:
  devstack_default:
    external: true

volumes:
  enterprise_subsidy_mysql57:
